baseURL = "https://altyncev.ru"
title = "Altyncev Vladislav"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "ru"
defaultExtension = "html"
defaultLayout = "post"

# disableKinds = ['taxonomy', 'term', 'section', 'home', 'page']

publishDir = "public"
buildDrafts = false
canonifyURLs = true

pluralizeListTitles = false
preserveTaxonomyNames = true

paginate = 20

enableRobotsTXT = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "npofopr"

YandexMetrika = "17143639"
domainVerification = "Zlo3LpLuAc13baEPecZMFGiRGwIyip_MGbS9NCQT17M"
googleAnalytics = "UA-2789259-4"
googleVerification = "Zlo3LpLuAc13baEPecZMFGiRGwIyip_MGbS9NCQT17M"
yandexVerification = "496c60b178050fff"

[params]
  author = "Vladislav Altyncev"
  info = "HTML coder ;-)"
  description = "Пишу о работе, жизни и обо всём, что понравится. PS: А я чё? Я ничё. Другие вон чё, и ничё, а я чуть чё, и сразу вон чё!"
  keywords = "blog,developer,personal"
  avatarurl = "/images/profile.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/favicon-32x32.png"
  favicon_16 = "/favicon-16x16.png"

  dateFormat = "January 2, 2006"

  # Git Commit in Footer, uncomment the line below to enable it.
  commit = "https://github.com/npofopr/_altyncev/tree/"

  footercontent = "Welcome."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  viewMorePostLink = "/blog/"

  # customCSS = ["css/custom.css"]
  customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = "html"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/npofopr"
[[params.social]]
  name = "Bitbucket"
  icon = "fa fa-bitbucket fa-2x"
  weight = 2
  url = "https://bitbucket.com/npofopr"
[[params.social]]
  name = "Instagramm"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/npofopr/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/npofopr"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 5
  url = "https://facebook.com/npofopr"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 6
  url = "https://t.me/npofopr"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog/"
[[menu.main]]
  name = "Handmade"
  url = "categories/cottage/"
  weight = 3
[[menu.main]]
  name = "Portfolio"
  url = "portfolio/"
  weight = 4
[[menu.main]]
  name = "Categories"
  url = "categories/"
  weight = 5
